workflows:
  ios-testflight:
    name: Helmly iOS → TestFlight
    max_build_duration: 60
    environment:
      groups:
        - app-store
      ios_signing:
        provisioning_profiles:
          - $PROVISIONING_PROFILE
        certificates:
          - certificate: $CERTIFICATE_PUBLIC_DATA
            private_key: $CERTIFICATE_PRIVATE_KEY
      vars:
        XCODE_PROJECT: "ios/App/App.xcodeproj"
        XCODE_SCHEME: "App"
        APP_STORE_APPLE_ID: 6771184542
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install Capacitor CLI
        script: npm install
      - name: Capacitor sync
        script: npx cap sync ios
      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install
      - name: Set app version
        script: |
          BUILD_NUMBER=$(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_APPLE_ID") + 1))
          cd ios/App
          agvtool new-version -all $BUILD_NUMBER
    artifacts:
      - ios/App/build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
